Nft tutorial using foundry and solmate
onbjerg/foundry-book pull request #107
Opened 2022-03-16 18:16 UTC by FredCoen

Following @gakonst request (https://twitter.com/gakonst/status/1488251153444147200) to showcase writing and testing and NFT with foundry this is the implementation of it.

2022-03-16 20:22 UTC, gakonst requested changes
nice work! some ideas

2022-03-16 20:22 UTC, gakonst commented on src/tutorials/creating-an-NFT-with-solmate-and-forge.md
> +cast call --rpc-url=$RPC_URL --private-key=$PRIVATE_KEY <contractAddress> "ownerOf(uint256)" 0
not needed

```suggestion
cast call --rpc-url=$RPC_URL <contractAddress> "ownerOf(uint256)(address)" 0
```

2022-03-16 20:22 UTC, gakonst commented on src/tutorials/creating-an-NFT-with-solmate-and-forge.md
> +import "openzeppelin-contracts/contracts/utils/Counters.sol";
no counters sir

2022-03-16 20:22 UTC, gakonst commented on src/tutorials/creating-an-NFT-with-solmate-and-forge.md
> +       bytes32 loc = bytes32(abi.encode(slot));
Think the `abi.encode` is not needed?

2022-03-16 20:22 UTC, gakonst commented on src/tutorials/creating-an-NFT-with-solmate-and-forge.md
> +       return bytes4(keccak256("onERC721Received(address,address,uint256,bytes)"));
think you can make this `this.onERC721Received.selector`

2022-03-16 20:22 UTC, gakonst commented on src/tutorials/creating-an-NFT-with-solmate-and-forge.md
> +That's it, I hope this will give you a good practical basis of how to get started with foundry. In my opinion there is no better way to deeply understand solidity than writing your tests in solidity.
Would recommend changing this to use "we" or avoid referring to self altogether (i.e. use third person)

2022-03-17 18:10 UTC, FredCoen commented
@gakonst thanks for review :) implemented the requested changes

2022-03-17 21:03 UTC, gakonst approved these changes

2022-03-19 18:55 UTC, FredCoen commented
this good to be merged? @onbjerg @gakonst

2022-03-19 20:18 UTC, gakonst commented
I think so? @onbjerg if you wanna give it a pass, it lgtm from..a high level

2022-03-21 08:48 UTC, onbjerg requested changes
Really appreciate this! Apologize for the late turnaround, I've been busy :disappointed: I've added some comments - feel free to just click "Commit suggestion" if you agree with them, don't worry too much about the commit log since it will be squashed.

Let me know if you have any questions, and again I apologize for the late turnaround!

2022-03-21 08:48 UTC, onbjerg commented on src/SUMMARY.md
> +  - [Creating an NFT with solmate and forge](./tutorials/creating-an-NFT-with-solmate-and-forge.md)
nit: Would just rename it to `solmate-nft.md` for shorter, consistent file names

2022-03-21 08:48 UTC, onbjerg commented on src/tutorials/creating-an-NFT-with-solmate-and-forge.md
> +This tutorial will run you through the steps create an Opensea compatible NFT and essentially rewrites this [guide](https://docs.opensea.io/docs/getting-started-1), while swapping hardhat  for foundr
Some wording and general conciseness

```suggestion
This tutorial walk you through creating an OpenSea compatible NFT with Foundry and [Solmate](https://github.com/Rari-Capital/solmate/blob/main/src/tokens/ERC721.sol). A full implementation of this tutorial can be found [here](https://github.com/FredCoen/nft-tutorial).
```

2022-03-21 08:48 UTC, onbjerg commented on src/tutorials/creating-an-NFT-with-solmate-and-forge.md
> +Start by setting up a foundry project following the steps outlined in the [Getting started section](https://onbjerg.github.io/foundry-book/getting-started/index.html). Furthermore we will install req
```suggestion
Start by setting up a Foundry project following the steps outlined in the [Getting started section](../getting-started). We will also install Solmate for their ERC721 implementation, as well as some OpenZeppelin utility libraries. Install the dependencies by running the following commands from the root of your project:
```

2022-03-21 08:48 UTC, onbjerg commented on src/tutorials/creating-an-NFT-with-solmate-and-forge.md
> +Let's rename the boilerplate src/Contract.sol to src/NFT.sol and copy the following code into your renamed file.
```suggestion
We are then going to rename the boilerplate contract in `src/Contract.sol` to `src/NFT.sol` and replace the code:
```

2022-03-21 08:48 UTC, onbjerg commented on src/tutorials/creating-an-NFT-with-solmate-and-forge.md
> +Let's take a look at this very basic implementation of an NFT. We start by importing to contracts from our git submodules. We import solmate's gas optimised implementation of the ERC721 standard whic
```suggestion
Let's take a look at this very basic implementation of an NFT. We start by importing to contracts from our git submodules. We import solmate's gas optimised implementation of the ERC721 standard which our NFT contract will inherit from. Our constructor takes the `_name` and `_symbol` arguments for our NFT and passes them on to the constructor of the parent ERC721 implementation. Lastly we implement the `mintTo` function which allows anyone to mint an NFT. This function increments the `currentTokenId` and makes use of the `_safeMint` function of our parent contract.
```

2022-03-21 08:48 UTC, onbjerg commented on src/tutorials/creating-an-NFT-with-solmate-and-forge.md
> +To compile the NFT contract run ```forge build```. By default the compiler output will reside in the out directory. To deploy our compiled contract with forge we have to set environment variables for
```suggestion
To compile the NFT contract run ``forge build``. By default the compiler output will be in the `out` directory. To deploy our compiled contract with Forge we have to set environment variables for the RPC endpoint and the private key we want to use to deploy.
```

2022-03-21 08:48 UTC, onbjerg commented on src/tutorials/creating-an-NFT-with-solmate-and-forge.md
> +Once set you can deploy your NFT with forge running the below command while adding the relevant constructor arguments to the NFT contract:
```suggestion
Once set, you can deploy your NFT with Forge by running the below command while adding the relevant constructor arguments to the NFT contract:
```

2022-03-21 08:48 UTC, onbjerg commented on src/tutorials/creating-an-NFT-with-solmate-and-forge.md
> +If successfully deployed, you will see the deploying wallet's address, the contract's address as well as the transaction hash printed to your console.
```suggestion
If successfully deployed, you will see the deploying wallet's address, the contract's address as well as the transaction hash printed to your terminal.
```

2022-03-21 08:48 UTC, onbjerg commented on src/tutorials/creating-an-NFT-with-solmate-and-forge.md
> +Calling functions on your NFT contract is made simple with foundry's cast, a command-line tool for interacting with EVM smart contracts, sending transactions, and getting chain data. Let's have a loo
```suggestion
Calling functions on your NFT contract is made simple with Cast, Foundry's command-line tool for interacting with smart contracts, sending transactions, and getting chain data. Let's have a look at how we can use it to mint NFTs from our NFT contract.
```

2022-03-21 08:48 UTC, onbjerg commented on src/tutorials/creating-an-NFT-with-solmate-and-forge.md
> +Well done, you just minted your first NFT from your contract. You can sanity check the owner of the NFT with currentTokenId equal to **0** by running the below ```cast call``` command. The address yo
```suggestion
Well done! You just minted your first NFT from your contract. You can sanity check the owner of the NFT with `currentTokenId` equal to **0** by running the below ``cast call`` command. The address you provided above should be returned as the owner.
```

2022-03-21 08:48 UTC, onbjerg commented on src/tutorials/creating-an-NFT-with-solmate-and-forge.md
> +Next, we will extend our NFT by adding metadata to represent the content of our NFTs, as well as set a minting price, a maximum supply and the possibility to withdraw the collected proceeds from mint
```suggestion
Let's extend our NFT by adding metadata to represent the content of our NFTs, as well as set a minting price, a maximum supply and the possibility to withdraw the collected proceeds from minting. To follow along you can replace your current NFT contract with the code snippet below:
```

2022-03-21 08:48 UTC, onbjerg commented on src/tutorials/creating-an-NFT-with-solmate-and-forge.md
> +Among others we have added metadata that can be queried from any front end application like Opensea by calling the tokenURI method on our Nft contract. **Note**: If you actually want to provide a rea
```suggestion
Among other things, we have added metadata that can be queried from any front-end application like OpenSea, by calling the `tokenURI` method on our NFT contract.

>**Note**: If you want to provide a real URL to the constructor at deployment, and host the metadata of this NFT contract please follow the steps outlined [here](https://docs.opensea.io/docs/part-3-adding-metadata-and-payments-to-your-contract#intro-to-nft-metadata).
```

2022-03-21 08:48 UTC, onbjerg commented on src/tutorials/creating-an-NFT-with-solmate-and-forge.md
> +Let's test some of this added functionality to make sure it works as intended. Foundry offers an extremely fast EVM native testing framework through forge.
```suggestion
Let's test some of this added functionality to make sure it works as intended. Foundry offers an extremely fast EVM native testing framework through Forge.
```

2022-03-21 08:48 UTC, onbjerg commented on src/tutorials/creating-an-NFT-with-solmate-and-forge.md
> +Within your test folder rename the current Contract.t.sol test file to NFT.t.sol. This file will contain all tests regarding the NFT's mintTo method. Next, replace the existing boilerplate code with
```suggestion
Within your test folder rename the current `Contract.t.sol` test file to `NFT.t.sol`. This file will contain all tests regarding the NFT's `mintTo` method. Next, replace the existing boilerplate code with the below:
```

2022-03-21 08:48 UTC, onbjerg commented on src/tutorials/creating-an-NFT-with-solmate-and-forge.md
> +
```suggestion
```

2022-03-21 08:48 UTC, onbjerg commented on src/tutorials/creating-an-NFT-with-solmate-and-forge.md
> +The test suite is set up as a contract with a setUp method which runs before every individual test. As you can see forge offers a number of [cheatcodes](https://onbjerg.github.io/foundry-book/forge/c
```suggestion
The test suite is set up as a contract with a `setUp` method which runs before every individual test.

As you can see, Forge offers a number of [cheatcodes](../forge/cheatcodes) to manipulate state to accomodate your testing scenario.

For example, our `testFailMaxSupplyReached` test checks that an attempt to mint fails when the max supply of NFT is reached. Thus, the `currentTokenId` of the NFT contract needs to be set to the max supply by using the store cheatcode which allows you to write data to your contracts storage slots. The storage slots you wish to write to can easily be found using the
```

2022-03-21 08:48 UTC, onbjerg commented on src/tutorials/creating-an-NFT-with-solmate-and-forge.md
> +forge-std helper library. You can run the test with the following command:
```suggestion
[`forge-std`](https://github.com/brockelmore/forge-std/) helper library. You can run the test with the following command:
```

2022-03-21 08:48 UTC, onbjerg commented on src/tutorials/creating-an-NFT-with-solmate-and-forge.md
> +If you want to put your forge skills to practice, write tests for the remaining methods of our NFT contract. Feel free to PR them [nft-tutorial]((https://github.com/FredCoen/nft-tutorial) where you w
```suggestion
If you want to put your Forge skills to practice, write tests for the remaining methods of our NFT contract. Feel free to PR them to [nft-tutorial]((https://github.com/FredCoen/nft-tutorial), where you will find the full implemenation of this tutorial.
```

2022-03-21 08:48 UTC, onbjerg commented on src/tutorials/creating-an-NFT-with-solmate-and-forge.md
> +Foundry provides a comprehensive gas report about your contracts. For every function called within your tests it returns the min, average, median and max gas cost. To print the gas report simply run:
```suggestion
Foundry provides comprehensive gas reports about your contracts. For every function called within your tests it, returns the minimum, average, median and max gas cost. To print the gas report simply run:
```

2022-03-21 08:48 UTC, onbjerg commented on src/tutorials/creating-an-NFT-with-solmate-and-forge.md
> +This comes in handy when looking at various gas optimizations within your contracts. Since we used Solmate gas optimised ERC721 library instead of OpenZeppelin's ERC721 library, let's have a look at
```suggestion
This comes in handy when looking at various gas optimizations within your contracts.

Let's have a look at the gas savings we made by substituting OpenZeppelin with Solmate for our ERC721 implementation. You can find the NFT implementation using both libraries [here](https://github.com/FredCoen/nft-tutorial). Below are the resulting gas reports when running ``forge test --gas-report`` on that repository.

As you can see, our implementation using Solmate saves around 500 gas on a successful mint (the max gas cost of the `mintTo` function calls).
```

2022-03-21 09:29 UTC, onbjerg commented
Thank you so much!

@all-contributors add @FredCoen for tutorial

2022-03-21 09:30 UTC, merged

2022-03-21 09:30 UTC, FredCoen commented
thanks for the thorough review @onbjerg :) and thanks for building this amazing tooling. Next I will implement a full test suite in foundry for an nft merkle drop. 
Implemented all your suggested changes on this one!