feat: docs for gas-reports
onbjerg/foundry-book pull request #64
Opened 2022-02-28 21:27 UTC by rootulp

Fixes https://github.com/onbjerg/foundry-book/issues/31

## Motivation
Epic feature needs docs

<img width="842" alt="Screen Shot 2022-02-28 at 4 24 45 PM" src="https://user-images.githubusercontent.com/3699047/156061059-06b813c6-507a-4fc4-99d3-f556a69f7e22.png">

## Screenshots

Added to `foundry.toml` Reference

<img width="746" alt="Screen Shot 2022-02-28 at 4 14 32 PM" src="https://user-images.githubusercontent.com/3699047/156061142-967f57a6-b159-4ab4-9a5f-faa73dac8b11.png">

New page: Gas reports

<img width="815" alt="Screen Shot 2022-02-28 at 4 22 18 PM" src="https://user-images.githubusercontent.com/3699047/156061129-58979574-d8da-43b5-8b73-e1ef9d255502.png">

2022-02-28 21:29 UTC, rootulp commented on src/reference/config.md
> +- Environment: `FOUNDRY_GAS_REPORTS` or `DAPP_GAS_REPORTS` // TODO confirm if these exist
draft PR because I don't know if the env variables: `FOUNDRY_GAS_REPORTS` or `DAPP_GAS_REPORTS` exist. I don't see them in https://github.com/gakonst/foundry/pull/637 or in Github [search](https://github.com/gakonst/foundry/search?q=FOUNDRY_GAS_REPORTS). 

Do reviewers know if they exist? Or should I remove this line?

2022-03-01 07:22 UTC, onbjerg commented on src/reference/config.md
> +- Environment: `FOUNDRY_GAS_REPORTS` or `DAPP_GAS_REPORTS` // TODO confirm if these exist
Yep, they automatically exist because of this line: https://github.com/gakonst/foundry/blob/2d1713f4052cae92a178a3c8e3bacb7ad6a4e359/config/src/lib.rs#L563 😄

2022-03-01 07:23 UTC, onbjerg requested changes
You should update the index in `src/forge/tests.md` and remove the todo, otherwise lgtm overall, thanks for this 😄

2022-03-01 15:14 UTC, rootulp commented on src/reference/config.md
> +- Environment: `FOUNDRY_GAS_REPORTS` or `DAPP_GAS_REPORTS` // TODO confirm if these exist
thanks for explaining!

2022-03-01 22:35 UTC, onbjerg commented
Ah, my bad, I remember it as an index. Thanks! :smile:

2022-03-01 22:35 UTC, merged

2022-03-02 00:07 UTC, rootulp commented
No problemo, thanks for maintaining these super helpful docs